#pragma once

#include <Arduino.h>

extern const uint8_t kMdiTv50Bmp[] PROGMEM;
extern const size_t kMdiTv50BmpSize;
extern const uint8_t kMdiPlaystation50Bmp[] PROGMEM;
extern const size_t kMdiPlaystation50BmpSize;
extern const uint8_t kMdiMusic50Bmp[] PROGMEM;
extern const size_t kMdiMusic50BmpSize;
extern const uint8_t kMdiRecord50Bmp[] PROGMEM;
extern const size_t kMdiRecord50BmpSize;
extern const uint8_t kMdiHome22Bmp[] PROGMEM;
extern const size_t kMdiHome22BmpSize;
extern const uint8_t kMdiPlay22Bmp[] PROGMEM;
extern const size_t kMdiPlay22BmpSize;
extern const uint8_t kMdiLight22Bmp[] PROGMEM;
extern const size_t kMdiLight22BmpSize;
extern const uint8_t kMdiInfo22Bmp[] PROGMEM;
extern const size_t kMdiInfo22BmpSize;
extern const uint8_t kMdiDots22Bmp[] PROGMEM;
extern const size_t kMdiDots22BmpSize;
extern const uint8_t kMdiPower18Bmp[] PROGMEM;
extern const size_t kMdiPower18BmpSize;
extern const uint8_t kMdiUp42Bmp[] PROGMEM;
extern const size_t kMdiUp42BmpSize;
extern const uint8_t kMdiDown42Bmp[] PROGMEM;
extern const size_t kMdiDown42BmpSize;
extern const uint8_t kMdiLeft42Bmp[] PROGMEM;
extern const size_t kMdiLeft42BmpSize;
extern const uint8_t kMdiRight42Bmp[] PROGMEM;
extern const size_t kMdiRight42BmpSize;
extern const uint8_t kMdiBack28Bmp[] PROGMEM;
extern const size_t kMdiBack28BmpSize;
extern const uint8_t kMdiHome28Bmp[] PROGMEM;
extern const size_t kMdiHome28BmpSize;
extern const uint8_t kMdiBox23Bmp[] PROGMEM;
extern const size_t kMdiBox23BmpSize;
extern const uint8_t kMdiTv23Bmp[] PROGMEM;
extern const size_t kMdiTv23BmpSize;
extern const uint8_t kMdiMusic23Bmp[] PROGMEM;
extern const size_t kMdiMusic23BmpSize;
extern const uint8_t kMdiSpeaker23Bmp[] PROGMEM;
extern const size_t kMdiSpeaker23BmpSize;
extern const uint8_t kMdiVolume48Bmp[] PROGMEM;
extern const size_t kMdiVolume48BmpSize;
extern const uint8_t kMdiMute48Bmp[] PROGMEM;
extern const size_t kMdiMute48BmpSize;
extern const uint8_t kMdiPower48Bmp[] PROGMEM;
extern const size_t kMdiPower48BmpSize;
extern const uint8_t kMdiHdmi48Bmp[] PROGMEM;
extern const size_t kMdiHdmi48BmpSize;
extern const uint8_t kMdiRecord48Bmp[] PROGMEM;
extern const size_t kMdiRecord48BmpSize;
extern const uint8_t kMdiSpeaker48Bmp[] PROGMEM;
extern const size_t kMdiSpeaker48BmpSize;
extern const uint8_t kMdiTv48Bmp[] PROGMEM;
extern const size_t kMdiTv48BmpSize;
extern const uint8_t kMdiHome48Bmp[] PROGMEM;
extern const size_t kMdiHome48BmpSize;
extern const uint8_t kMdiBack48Bmp[] PROGMEM;
extern const size_t kMdiBack48BmpSize;
extern const uint8_t kMdiVolumeMinus32Bmp[] PROGMEM;
extern const size_t kMdiVolumeMinus32BmpSize;
extern const uint8_t kMdiVolumePlus32Bmp[] PROGMEM;
extern const size_t kMdiVolumePlus32BmpSize;
extern const uint8_t kMdiSkipPrev32Bmp[] PROGMEM;
extern const size_t kMdiSkipPrev32BmpSize;
extern const uint8_t kMdiSkipNext32Bmp[] PROGMEM;
extern const size_t kMdiSkipNext32BmpSize;
extern const uint8_t kMdiPlayPause38Bmp[] PROGMEM;
extern const size_t kMdiPlayPause38BmpSize;
extern const uint8_t kMdiRadioMarked28Bmp[] PROGMEM;
extern const size_t kMdiRadioMarked28BmpSize;
extern const uint8_t kMdiRewind30Bmp[] PROGMEM;
extern const size_t kMdiRewind30BmpSize;
extern const uint8_t kMdiFastForward30Bmp[] PROGMEM;
extern const size_t kMdiFastForward30BmpSize;
extern const uint8_t kMdiPlayPause30Bmp[] PROGMEM;
extern const size_t kMdiPlayPause30BmpSize;
extern const uint8_t kMdiHdmi36Bmp[] PROGMEM;
extern const size_t kMdiHdmi36BmpSize;
extern const uint8_t kMdiRecord36Bmp[] PROGMEM;
extern const size_t kMdiRecord36BmpSize;
extern const uint8_t kMdiBack36Bmp[] PROGMEM;
extern const size_t kMdiBack36BmpSize;
extern const uint8_t kMdiWifi36Bmp[] PROGMEM;
extern const size_t kMdiWifi36BmpSize;
extern const uint8_t kMdiBluetooth36Bmp[] PROGMEM;
extern const size_t kMdiBluetooth36BmpSize;
extern const uint8_t kMdiVolMinus42Bmp[] PROGMEM;
extern const size_t kMdiVolMinus42BmpSize;
extern const uint8_t kMdiMute42Bmp[] PROGMEM;
extern const size_t kMdiMute42BmpSize;
extern const uint8_t kMdiVolPlus42Bmp[] PROGMEM;
extern const size_t kMdiVolPlus42BmpSize;
